---
- get_facts:
    interface_list:
      _mode: strict
      list:      
        - GigabitEthernet2
      
        - GigabitEthernet1
      
        - GigabitEthernet4
      
        - GigabitEthernet3
        - Loopback0
    hostname: PE2

- get_bgp_neighbors:
    global:
      router_id: 10.3.3.3
      peers:
        _mode: strict
        10.1.1.1:
          is_enabled: true
          is_up: true
          remote_id: 10.1.1.1
          remote_as: 65001
          local_as: 65001

- get_interfaces_ip:
    GigabitEthernet2:
      ipv4:
        10.203.55.6:
          prefix_length: 30
    GigabitEthernet1:
      ipv4:
        10.203.55.13:
          prefix_length: 30
    GigabitEthernet4:
      ipv4:
        10.203.55.129:
          prefix_length: 30
    GigabitEthernet3:
      ipv4:
        10.0.10.204:
          prefix_length: 24
    Loopback0:
      ipv4:
        10.3.3.3:
          prefix_length: 32

- ping:
    _name: ping_P1
    _kwargs:
      destination: 10.2.2.2
      source: 10.3.3.3
    success:
      packet_loss: 0
    _mode: strict

- ping:
    _name: ping_PE1
    _kwargs:
      destination: 10.1.1.1
      source: 10.3.3.3
    success:
      packet_loss: 0
    _mode: strict

