---
- name: Gather napalm facts and create basic report
  hosts: all
  connection: local
  gather_facts: no
  vars:
  - output_path: output
  - template_path: templates

  tasks:
  - name: Get facts with napalm
    napalm_get_facts: 
      hostname: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      dev_os: 'ios'   
      password: "{{ ansible_ssh_pass }}"
      filter: 
        - 'facts'
        - 'interfaces'
        - 'interfaces_ip'
        - 'ntp_stats'
    register: result
 
  - name: Create output directory
    file:
      path: "{{ output_path }}"
      state: directory
    run_once: true
  
  - name: Clean up old report
    file:
      path: "{{ output_path }}/basic_report.html"
      state: absent
    run_once: true
  
  - name: Create report
    template:
      src: "{{ template_path }}/basic.j2"
      dest: "{{ output_path }}/basic_report.html"
    run_once: true