---
- name: Test Inventory
  hosts: all
  connection: local
  gather_facts: no
  vars:
  - output_path: output
  - template_path: templates
  - textfsm_template_path: ../../ntc-templates/templates

  tasks:
  - name: Get facts with napalm
    napalm_get_facts: 
      hostname: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      dev_os: 'ios'   
      password: "{{ ansible_ssh_pass }}"
      filter: 
        - 'facts'
        - 'interfaces'
        - 'interfaces_ip'
        - 'ntp_stats'
    register: result
  #- debug: msg="{{ result }}"
  
  - name: Get OSPF neighbors
    ios_command:
      commands: show ip ospf neighbor
    register: result

  - debug: msg="{{ result }}"

  - set_fact: 
      ospf_neighbor: {{ result | parse_cli_textfsm('{{ textfsm_template_path }}/cisco_ios_show_ip_ospf_neighbor.template') }}

  - name: Create directory
    file:
      path: "{{ output_path }}"
      state: directory
    run_once: true
  #- debug: var=vars
  
  - name: Create report
    template:
      src: "{{ template_path }}/basic.j2"
      dest: "{{ output_path }}/basic_report.html"
    run_once: true

  