---
- name: Save IOS facts
  hosts: all
  #serial: 2
  gather_facts: no
  vars:
  - output_path: output
  - template_path: templates
  tasks:
  - name: Gather IOS facts
    ios_facts:
      gather_subset: 
        - all
  - ios_command:
      commands: show version
    register: version
  - set_fact:
      uptime: "{{ version.stdout[0]|regex_search('uptime is (.+)') }}"
  - file:
      path: "{{ output_path }}"
      state: directory
    run_once: true
  #- debug: var=vars
  - template:
      src: "{{ template_path }}/uptime.j2"
      dest: "{{ output_path }}/uptimes.csv"
    run_once: true
  #- debug: var=vars.ansible_facts
  #- local_action: >
  #    copy content="{{ vars.ansible_facts }}" 
  #         dest="{{ output_path }}/{{ ansible_net_hostname }}_facts.json"
