---
- name: Test Inventory
  hosts: all
  connection: local
  gather_facts: no

  tasks:                      
    - napalm_get_facts: 
      #optional_args: {'secret': password}  #
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        dev_os: 'ios'   
        password: "{{ ansible_ssh_pass }}"
        filter: 'facts'
      register: result              

    - debug: msg="{{ result }}"