---
- get_facts:
    interface_list:
      _mode: strict
      list:      
        - GigabitEthernet1
      
        - GigabitEthernet2
      
        - GigabitEthernet3
      
        - GigabitEthernet4
        - Loopback0
    hostname: CE3


- get_interfaces_ip:
    GigabitEthernet1:
      ipv4:
        10.203.55.17:
          prefix_length: 30
    GigabitEthernet3:
      ipv4:
        10.0.10.206:
          prefix_length: 24
    Loopback0:
      ipv4:
        172.16.3.3:
          prefix_length: 32

- ping:
    _name: ping_CE4
    _kwargs:
      destination: 172.16.4.4
      source: 172.16.3.3
    success:
      packet_loss: 0
    _mode: strict

