---
- hosts: localhost
  gather_facts: no
  vars:
    - template_path: templates
    - output_path: output
  vars_files: [fabric.yml]
  tasks:
    - name: Generate linknets
      template:
        src: "{{ template_path }}/generate_linknets.j2"
        dest: "{{ output_path }}/linknets.csv"