---
- hosts: localhost
  gather_facts: no
  vars:
    - template_path: templates
    - output_path: output
  vars_files: [fabric.yml, ip_addresses.yml]
  tasks:
    - name: Create output directory
      file:
        path: "{{ output_path }}"
        state: directory

    - name: Generate linknets
      template:
        src: "{{ template_path }}/generate_linknets.j2"
        dest: "{{ output_path }}/ip_addresses.yml"
