---
- name: Deploy config
  hosts: all
  connection: local
  gather_facts: no
  vars:
  - config_path: configs
  - output_path: reports
  - template_path: templates
  vars_files: [nodes.yml]

  tasks:
  - name: Deploy init config
    ios_config:
      src: "{{ config_path }}/{{ inventory_hostname }}/basic.cfg"
    tags: deploy_init
    register: changes

  - name: Deploy network config
    ios_config:
      src: "{{ config_path }}/{{ inventory_hostname }}/running.cfg"
    tags: deploy_network
    register: changes

  - name: Find service config file size
    stat:
      path: '{{ config_path }}/{{ inventory_hostname }}/service.cfg'
    register: service
    tags: deploy_service

  - name: Deploy service config with napalm
    napalm_install_config:
      provider: '{{ ios_provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/service.cfg'
      commit_changes: True
      replace_config: False
      get_diffs: True
      diff_file: '{{ config_path}}/{{ inventory_hostname }}/service.diff'
      when: service.stat.size > 0
    tags: deploy_service

  - name: Validate device config
    napalm_validate:
      provider: "{{ ios_provider }}"
      validation_file: "{{ config_path }}/{{ inventory_hostname }}/validate.yml"
    register: report
    tags: validate

  - name: Create output directory
    file:
      path: "{{ config_path }}/{{ inventory_hostname }}"
      state: directory
    tags: validate
  
  - name: Clean up old report
    file:
      path: "{{ config_path }}/{{ inventory_hostname }}/validation_report.html"
      state: absent
    tags: validate
  
  - name: Create validation report
    template:
      src: "{{ template_path }}/validation_report.j2"
      dest: "{{ config_path }}/{{ inventory_hostname }}/validation_report.html"
    tags: validate