---
- name: Deploy config
  hosts: cust
  connection: local
  gather_facts: no
  vars:
  - config_path: configs

  tasks:
  - name: Get facts with napalm
    napalm_get_facts: 
      provider: '{{ provider }}'
      filter: 
        - 'facts'
        - 'interfaces'
        - 'interfaces_ip'
        - 'ntp_stats'
    register: result
  #- debug: var=vars.result

  # something something, set : ip scp server enable
  #                      mkdir flash:/backups/
  #                      set : archive
  #                             path flash:/backups/
  # nuke cert? : no crypto pki trustpoint TP-self-signed-xxxxx

  #- 

  - name: put config with napalm
    napalm_install_config:
      hostname: '{{ ansible_host }}'
      username: '{{ ansible_user }}'
      dev_os: 'ios'
      password: '{{ ansible_ssh_pass }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}.cfg'
      commit_changes: True
      replace_config: True
      get_diffs: True
      diff_file: '{{ config_path}}/{{ inventory_hostname }}.diff'