---
- name: Deploy config
  hosts: all
  connection: local
  gather_facts: no
  vars:
  - config_path: configs

  tasks:
  - name: Deploy init config
    ios_config:
      #provider: "{{ ios_provider }}"
      src: "{{ config_path }}/{{ inventory_hostname }}/basic.cfg"
    tags: deploy_init
    register: changes

  - name: Deploy init config with napalm
    napalm_install_config:
      provider: '{{ ios_provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/basic.cfg'
      commit_changes: True
      replace_config: False
      get_diffs: True
      diff_file: '{{ config_path}}/{{ inventory_hostname }}/basic.diff'
    tags: deploy_init_napalm

  - name: Deploy network config
    ios_config:
      #provider: "{{ ios_provider }}"
      src: "{{ config_path }}/{{ inventory_hostname }}/running.cfg"
    tags: deploy_network
    register: changes
  
  - debug: var=vars.changes

  - name: Deploy network config with napalm
    napalm_install_config:
      provider: '{{ ios_provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/running.cfg'
      commit_changes: True
      replace_config: False
      get_diffs: True
      diff_file: '{{ config_path}}/{{ inventory_hostname }}/running.diff'
    tags: deploy_network_napalm

  - name: Deploy service config with napalm
    napalm_install_config:
      provider: '{{ ios_provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/service.cfg'
      commit_changes: True
      replace_config: False
      get_diffs: True
      diff_file: '{{ config_path}}/{{ inventory_hostname }}/service.diff'
    tags: deploy_service

  - name: get validate report
    napalm_validate:
      provider: "{{ ios_provider }}"
      validation_file: "{{ config_path }}/{{ inventory_hostname }}/validate.yml"
    register: report
    tags: validate

  - debug: var=vars.report