---
- name: Deploy config
  hosts: cust
  connection: local
  gather_facts: no
  vars:
  - config_path: configs

  tasks:
  - name: Initialise device with basic config
    napalm_install_config:
      provider: '{{ ios_provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/basic.cfg'
      commit_changes: True
      replace_config: True
      get_diffs: False
    tags: init

  - name: put config with napalm
    napalm_install_config:
      provider: '{{ ios_provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/running.cfg'
      commit_changes: True
      replace_config: True
      get_diffs: True
      diff_file: '{{ config_path}}/{{ inventory_hostname }}/running.diff'
    tags: deploy_napalm

  - name: Deploy config
    ios_config:
      #provider: "{{ ios_provider }}"
      src: "{{ config_path }}/{{ inventory_hostname }}/running.cfg"
    tags: deploy_ios_config
    register: changes
  
  - debug: var=vars.changes

  - name: get validate report
    napalm_validate:
      provider: "{{ ios_provider }}"
      validation_file: "{{ config_path }}/{{ inventory_hostname }}/validate.yml"
    register: report
    tags: validate

  - debug: var=vars.report