---
- name: Deploy config
  hosts: cust
  connection: local
  gather_facts: no
  vars:
  - config_path: configs

  tasks:
  - name: Get facts with napalm
    napalm_get_facts: 
      provider: '{{ provider }}'
      filter: 
        - 'facts'
        - 'interfaces'
        - 'interfaces_ip'
        - 'ntp_stats'
    register: result
  #- debug: var=vars.result

  - name: Initialise device with basic config
    napalm_install_config:
      provider: '{{ provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/basic.cfg'
      commit_changes: True
      replace_config: True
      get_diffs: False
    tags: init

  - name: put config with napalm
    napalm_install_config:
      provider: '{{ provider }}'
      config_file: '{{ config_path }}/{{ inventory_hostname }}/running.cfg'
      commit_changes: True
      replace_config: True
      get_diffs: True
      diff_file: '{{ config_path}}/{{ inventory_hostname }}/running.diff'