---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    - template_path: templates
    - output_path: configs
  vars_files: [nodes.yml]
  
  tasks:
    - name: Clean up node config
      local_action:
        module: file
        path: "{{ output_path }}"
        state: absent
      run_once: true

    - name: Create output directories
      local_action:
        module: file
        path: "{{ output_path }}/{{ inventory_hostname }}"
        state: directory

    - name: Create config files for initialisation
      local_action:
        module: template
        src: '{{ template_path }}/basic.j2'
        dest: '{{ output_path }}/{{ inventory_hostname }}/basic.cfg'

    - name: Generate node config
      local_action:
        module: template
        src: "{{ template_path }}/generate_node_config.j2"
        dest: "{{ output_path }}/{{ inventory_hostname }}/running.cfg"
