---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    - template_path: templates
    - output_path: output
  vars_files: [nodes.yml]
  
  tasks:
    - name: Create output directory
      run_once: true
      local_action:
        module: file
        path: "{{ output_path }}"
        state: directory
    
    - name: Clean up node config
      local_action:
        module: file
        path: "{{ output_path }}/{{ inventory_hostname }}.cfg"
        state: absent

    - name: Generate node config
      template:
        src: "{{ template_path }}/generate_node_config.j2"
        dest: "{{ output_path }}/{{ inventory_hostname }}.cfg"
