---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    - template_path: templates
    - textfsm_show_vrf: 'templates/cisco_ios_xe_show_vrf.template'
  vars_files: [nodes.yml]

  tasks:
  - name: Get existing VRF
    ios_command:
      commands:
        - show vrf
    register: vrf
    tags: vrf_report
  
  - debug: var=vars.vrf

  - name: Extract existing VRFs with textfsm
    set_fact: 
      active_vrf: "{{ vrf.stdout[0] | parse_cli_textfsm(textfsm_show_vrf) }}"
    tags: vrf_report
  
  - debug: var=vars.active_vrf

  - name: Clean up vrf reports
    file:
      path: "existing_vrf.yml"
      state: absent
    run_once: true
    tags: vrf_report

  - name: Create existing VRF report
    template:
      src: "{{ template_path }}/generate_existing_vrf.j2"
      dest: "existing_vrf.yml"
    run_once: true
    tags: vrf_report