---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    - template_path: templates
    - textfsm_show_vrf: 'templates/cisco_ios_xe_show_vrf.template'
    - log_path: logging
  vars_files: [ nodes.yml ]

  tasks:
  - name: Create output directory
    file:
      path: "{{ log_path }}"
      state: directory
    run_once: true
    when: logging

  - name: Get existing VRF
    ios_command:
      commands:
        - show vrf
    register: vrf
    tags: vrf_report
  
  - local_action: copy content="{{ vrf|to_nice_json }}" dest="{{ log_path }}/{{ inventory_hostname }}_existing_vrf_{{ '%Y-%m-%d %H:%M:%S' | strftime }}.json"
    when: logging

  - name: Extract existing VRFs with textfsm
    set_fact: 
      active_vrf: "{{ vrf.stdout[0] | parse_cli_textfsm(textfsm_show_vrf) }}"
    tags: vrf_report

  - name: Clean up vrf reports
    file:
      path: "existing_vrf.yml"
      state: absent
    run_once: true
    tags: vrf_report

  - name: Create existing VRF report
    template:
      src: "{{ template_path }}/generate_existing_vrf.j2"
      dest: "existing_vrf.yml"
    run_once: true
    tags: vrf_report