---
- name: Pre-init devices
  hosts: all
  connection: local
  gather_facts: no
  vars:
  # something something, set : ip scp server enable
  #                      mkdir flash:/backups/
  #                      set : archive
  #                             path flash:/backups/
  # nuke cert? : no crypto pki trustpoint TP-self-signed-xxxxx
  tasks:
  - name: pre-init via serial
    telnet:
      prompts:
        - "[>|#]"
      command:
        - enable
        - conf t
        - interface GigabitEthernet3
        - ip address 10.0.10.201 255.255.255.0
        - exit
        - ip route 10.0.10.0 255.255.255.0 10.0.10.1
        - username admin privilege 15 secret paladin
        - line vty 0 4
        - 
        - end 
        - write memory



        - mkdir flash:/backups/
        - conf t
        - ip scp server enable
        - archive
        - path flash:/backups/
        - interface GigabitEthernet3
        - ip address 10.0.10.201
        - exit
        - ip route 10.0.10.0 255.255.255.0 10.0.10.1
        - sh crypto pki trustpoints
        - end
        - write memory
        #- exit
