# Validates all the inputs in the various vars files that everything is based on.
# See testing/test_validate_input.yml for all tests that are used.
---
- hosts: localhost
  gather_facts: no
  vars:
    - template_path: templates
    - report_path: reports
  vars_files: [fabric.yml, ip_addresses.yml, services.yml]

  tasks:
    - name: Create report directory
      local_action:
        module: file
        path: "{{ report_path }}"
        state: directory
      tags: j2

    - name: Validate that all vars are properly defined and not empty within a j2 template
      template:
        src: "{{ template_path }}/validate_vars.j2"
        dest: "{{ report_path }}/vars_validation_report_{{ '%Y%m%d%H%M%S'|strftime }}.txt"
      tags: j2
