# Runs the tests for generating node datamodels on each scenario defined
# in the scenario directory. 
---
- hosts: localhost
  gather_facts: no
  vars:
    - template_path: ../templates
    - report_path: test_reports
    - scenario_path: "{{ playbook_dir }}/scenario"

  tasks:
    - name: Create test report directory
      local_action:
        module: file
        path: "{{ report_path }}"
        state: directory

    - name: Find all test directories
      find:
        paths: "{{ scenario_path }}"
        recurse: no
        file_type: directory
      register: scenario_list

    - name: Loop over test node datamodel
      include: test_node_datamodel.yml scenario="{{ item.path.split('/')[-1] }}"
      with_items: "{{ scenario_list.files }}"
      tags: nodes

    - name: Loop over test input validate
      include: test_validate_input.yml scenario="{{ item.path.split('/')[-1] }}"
      with_items: "{{ scenario_list.files }}"
      tags: validate

    - name: Assemble all test reports
      local_action:
        module: assemble
        src: "{{ report_path }}"
        dest: "combined_test_report_{{ '%Y%m%d%H%M%S' | strftime }}.txt"
