---
- hosts: localhost
  gather_facts: no
  vars:
    - template_path: ../templates
    - output_path: output


  tasks:
    - name: Find all test directories
      find:
        paths: "{{ playbook_dir }}/scenario"
        recurse: no
        file_type: directory
      register: scenario_list

    #- debug: msg="{{ item.path.split('/')[-1] }}"
     # with_items: "{{ scenario_list.files }}"

    - name: Loop over tests
      include: test_node_datamodel.yml scenario="{{ item.path.split('/')[-1] }}"
      with_items: "{{ scenario_list.files }}"